### ISSUE TITLE
We talk about "agents" but never define the term.

### ISSUE THREAD

**Issue by harlantwood** [Mindonaut/Gravity#22]

**Comment by collincusce** [comment]
Thanks I literally was just trying to suss agent and agency right now.

**Comment by harlantwood** [comment]
Ah, I felt like I found what I needed when I got to https://github.com/GravityNetwork/Gravity/wiki/Gravity-Whitepaper#agents-agencies-and-capabilities -- @collincusce does that address your needs?

**Comment by collincusce** [comment]
Yes. I was just starting to read it when I wrote that. When you closed it, I ctrl-f'd to try and find where it was added. 

Personally, that section is a bit vague to me, but I'm still trying to grok the whole document. If you like I can submit feedback when I'm finished reading.

**Comment by harlantwood** [comment]
Yes please!

On Jun 28, 2017 4:14 PM, "Collin K Cusce" <notifications@github.com> wrote:

Yes. I was just starting to read it when I wrote that. When you closed it,
I ctrl-f'd to try and find where it was added.

Personally, that section is a big vague to me, but I'm still trying to grok
the whole document. If you like I can submit feedback when I'm finished
reading.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/GravityNetwork/Gravity/issues/22#issuecomment-311817846>,
or mute the thread
